version: '3.1'

services:
    generator:
      image: my-registry:55000/gen:ci-${GENERATOR_BUILD_NUMBER-10}
      ports:
       - 8081:80
    mail:
      image: mailhog/mailhog
      ports:
        - 8082:8025
  